### ISSUE TITLE
(PYL-W0301) Unnecessary semicolon

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#255]
## Description
Semicolons are not needed in Python unless using multiple statements in single line. Use of semi-colons add unnecessary clutter.

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/PYL-W0301/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/PYL-W0301/occurrences/)

**Comment by akshaygidwani404** [comment]
Hi @robotichead! Found this issue interesting. Could you please elaborate on what needs to be done?
