### ISSUE TITLE
(PYL-W0404) Multiple imports for an import name detected

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#256]
## Description
A module or an import name is reimported multiple times. This can be confusing and should be fixed. Please refer to the occurrence message to see the reimported name and the line number where it was imported for the first time.

## Occurrences
There are 11 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/PYL-W0404/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/PYL-W0404/occurrences/)

**Comment by pdavis327** [comment]
I submitted a PR for this

**Comment by robotichead** [comment]
Thank you :)
