### ISSUE TITLE
(PYL-W0613) Function contains unused argument

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#258]
## Description
An unused argument can lead to confusions. It should be removed. If this variable is necessary, name the variable `_` or start the name with `unused` or `_unused`.

## Occurrences
There is 1 occurrence of this issue in the repository.
There is also 1 function call in this repository that needs to be fixed also

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/PYL-W0613/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/PYL-W0613/occurrences/)

**Comment by Nagabharan1** [comment]
Can you help me solving this issue?

**Comment by robotichead** [comment]
Sure.

The decorator function `def check_permission_denied(min_permission_level):` has an unused variable `min_permission_level`. 

This particular variable can be removed from this function, and any of the function calls.

**Comment by robotichead** [comment]
Awesome news, your PR has been merged.

Thank you very much for your help :D
