### ISSUE TITLE
(FLK-E231) Missing whitespace after ',', ';', or ':'

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#262]
## Description
There should be whitespace after the characters `,`, `;`, and `:`.

## Occurrences
There are 342 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/FLK-E231/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/FLK-E231/occurrences/)

**Comment by NisargChokshi** [comment]
Hey @robotichead, I will do the necessary changes as per the DeepSource Analysis.
Could you please assign this to me?

**Comment by robotichead** [comment]
#265 provided a fix
