### ISSUE TITLE
(FLK-W292) No newline at end of file

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#286]
## Description
It is recommended to put a newline at the end of the file.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/FLK-W292/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/FLK-W292/occurrences/)

**Comment by Prashant0kgp** [comment]
Hi @robotichead, I would like to do my contribution.
plz, assign me if possible!!

**Comment by Vishvesh-Kodihal** [comment]
Hi @robotichead, I would like resolve this issue can you assign this to me.
