### ISSUE TITLE
(FLK-E501) Line too long

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#299]
## Description
Line length greater than configured `max_line_length` detected, defaults to 79 character. This limit can be configured [docs](https://deepsource.io/docs/analyzer/python/#meta)

## Occurrences
There are 293 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/FLK-E501/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/FLK-E501/occurrences/)

## Tips

`list_of_opportunity_stage(list_order="6", opportunity_stage_description="Perception Analysis", probability_success="60"),`

For the above line, we have the style;

```
list_of_opportunity_stage(
    list_order="6", 
    opportunity_stage_description="Perception Analysis", 
    probability_success="60"
),
```

For any Python imports, try and separate the lines with a simple `\`

```
from NearBeach.models import kanban_board, \
    kanban_card, \
    opportunity, \
    organisation, \
    quote, \
    project, \
    request_for_change, \
    requirement, \
    requirement_item, \
    task, \
    whiteboard
```

Good Luck :D

**Comment by drbalar** [comment]
Can you assign me this issue? @robotichead

**Comment by robotichead** [comment]
Hello @drbalar , I've assigned the task to you :)

**Comment by namangirdhar16** [comment]
@robotichead can you assign this to me?

**Comment by robotichead** [comment]
@namangirdhar16 assigned :)
