### ISSUE TITLE
(FLK-E302) Expected 2 blank lines

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#310]
## Description
Two blank lines are expected between functions and classes.

## Occurrences
There are 34 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/FLK-E302/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/FLK-E302/occurrences/)

**Comment by VishwajeetT22** [comment]
Hey @robotichead, due to some other work I am not able to work on this issue. Can you reassign it to someone else?

**Comment by namangirdhar16** [comment]
@robotichead i'm willing to work on this.

**Comment by Saatvat** [comment]
My PR #329 fixes this issue.
@robotichead can you please merge the above mentioned PR?
