### ISSUE TITLE
Latest docker image 

### ISSUE THREAD

**Issue by aidanjbennett** [robotichead/NearBeach#366]
**Describe the bug**
The latest docker image doesn't work I suspect it is because the image was made on a m1 mac.

**To Reproduce**
Steps to create the behavior:
1. Pull and run the latest docker tag on nearbeach on a linux machine.
2. Do docker logs and the container name
3. See error

**Expected behavior**
Near Beach to be running. 
**Actual Results**
It errors :(( 
**Useful infomation**
Docker logs https://sourceb.in/5lILRyHUHV 
System it is running on https://i.imgur.com/BAwWctT.png

**Comment by robotichead** [comment]
Compiling - issue was caused by not compiling for other architectures

**Comment by robotichead** [comment]
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/12730065/177655901-dab76823-5009-4874-ae87-7b4a13b76d5c.png">
@aidanjbennett - can you please check the latest build :)

**Comment by aidanjbennett** [comment]
I am happy to report that the latest image works now :)

**Comment by aidanjbennett** [comment]
> I am happy to report that the latest image works now :)



> <img alt="image" width="1285" src="https://user-images.githubusercontent.com/12730065/177655901-dab76823-5009-4874-ae87-7b4a13b76d5c.png">
> 
> @aidanjbennett - can you please check the latest build :)
> Hopefully not related to this issue - [robotichead/nearbeach-docker#4](https://github.com/robotichead/nearbeach-docker/issues/4)

I am happy to report that the latest image works now on my server.
