### ISSUE TITLE
(FLK-E303) Too many blank lines found

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#393]
## Description
Two blank lines are expected between functions and classes and one blank line is expected between methods of a class.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/FLK-E303/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/FLK-E303/occurrences/)

**Comment by moazfarrukh** [comment]
Can i work on this issue?

**Comment by AdeshChoudhar** [comment]
@robotichead I believe we can close this issue.

**Comment by robotichead** [comment]
Thank you @AdeshChoudhar :D
