### ISSUE TITLE
(JS-0246) Require template literals instead of string concatenation

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#395]
## Description
In ES2015 (ES6), we can use template literals instead of string concatenation.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/JS-0246/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/JS-0246/occurrences/)

**Comment by rosdyana** [comment]
Hi @robotichead I created PR for this, could you please check it, thanks :)
https://github.com/robotichead/NearBeach/pull/408
