### ISSUE TITLE
(FLK-E221) Multiple spaces found before operator

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#396]
## Description
There should be only one space before an operator.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/FLK-E221/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/FLK-E221/occurrences/)

**Comment by AdeshChoudhar** [comment]
@robotichead I believe we can close this issue.

**Comment by robotichead** [comment]
Thank you @AdeshChoudhar :D
