### ISSUE TITLE
(FLK-E713) Test for membership should be 'not in'

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#397]
## Description
Tests for membership should use the form `x not in the_list` rather than `not x in the_list`. The former example is simply more readable.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/robotichead/NearBeach/issue/FLK-E713/occurrences/](https://deepsource.io/gh/robotichead/NearBeach/issue/FLK-E713/occurrences/)

**Comment by dipanshusingh2107** [comment]
assign this to me

**Comment by robotichead** [comment]
Thank you :) I will close this issue
