### ISSUE TITLE
(PYL-R0123) Comparing to literal

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#481]
## Description
Comparing an object to a literal is usually something you do not want to do, since you can compare to a different literal than what was expected altogether.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/PYL-R0123/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/PYL-R0123/occurrences/)

**Comment by rasehgal** [comment]
can I make this fix? looks like a simple operator substitution

**Comment by Arun-Raghav-S** [comment]
@robotichead  I have fixed this issue. Could you please assign this issue to me and review my PR #507?
