### ISSUE TITLE
(JS-0712) Avoid `target='_blank'` attribute without `rel='noopener noreferrer'`

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#483]
## Description
A malicious actor can gain full control over the user&#x27;s DOM window object. This can lead to phishing attacks such as fake login prompts or password alerts being shown to the user.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/JS-0712/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/JS-0712/occurrences/)

**Comment by joshith3501** [comment]
Hey, I would like to work on this. Can you assign this issue to me?
