### ISSUE TITLE
(FLK-E305) Expected 2 blank lines after end of function or class

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#484]
## Description
Functions and classes should have two blank lines after them, separating them from other functions and classes.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/FLK-E305/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/FLK-E305/occurrences/)

**Comment by inkollusireeshaadharani** [comment]
Hi. Can you assign this issue to me please
