### ISSUE TITLE
(FLK-E261) At least two spaces before inline comment

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#485]
## Description
Inline comments should have two spaces before them.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/FLK-E261/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/FLK-E261/occurrences/)

**Comment by DezzaAnnePeregrina** [comment]
Hello, I would like to work on th

**Comment by Arun-Raghav-S** [comment]
@robotichead  Hey, I have solved this issue could you please review my PR #506
