### ISSUE TITLE
(JS-0246) Require template literals instead of string concatenation

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#486]
## Description
In ES2015 (ES6), we can use template literals instead of string concatenation.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/JS-0246/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/JS-0246/occurrences/)

**Comment by parasss19** [comment]
Hey i want to work on this issue

**Comment by Arun-Raghav-S** [comment]
@robotichead  I have raised a PR which fixes the issue please review it
