### ISSUE TITLE
(FLK-E271) Multiple spaces after keyword

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#487]
## Description
There should be only one space after a keyword.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/FLK-E271/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/FLK-E271/occurrences/)

**Comment by parasss19** [comment]
Hey i want to work on this issue

**Comment by Arun-Raghav-S** [comment]
@robotichead  Please review my PR #508 I have solved the issue
