### ISSUE TITLE
(JS-0239) Consider using `let` or `const` instead of `var`

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#489]
## Description
It is recommended to use `let` or `const` over `var`. This will help prevent re-declaration of variables that are in the global scope when using `var`.

## Occurrences
There are 91 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/JS-0239/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/JS-0239/occurrences/)

**Comment by Gowrishankar04** [comment]
Hi @robotichead,

Can I work on this?

**Comment by Ahnaf-codes** [comment]
@robotichead i would like to work on this
