### ISSUE TITLE
(PYL-R0201) Consider decorating method with `@staticmethod`

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#490]
## Description
The method doesn&#x27;t use its bound instance. Decorate this method with `@staticmethod` decorator, so that Python does not have to instantiate a bound method for every instance of this class thereby saving memory and computation. Read more about staticmethods [here](https://docs.python.org/3/library/functions.html#staticmethod).

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/PYL-R0201/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/PYL-R0201/occurrences/)

**Comment by DHRUVKHANDELWAL00** [comment]
hey @robotichead please assign me. i would like to work on it
