### ISSUE TITLE
(PTC-W0027) `f-string` used without any expression

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#491]
## Description
It is wasteful to use `f-string` mechanism if there are no expressions to be extrapolated. It is recommended to use regular strings instead.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/PTC-W0027/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/PTC-W0027/occurrences/)

**Comment by Mikerniker** [comment]
Hello, I'd like to try working on this issue if it's available. Thank you!
