### ISSUE TITLE
(JS-0050) Avoid use of `==` and `!=`

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#495]
## Description
It is considered good practice to use the type-safe equality operators `===` and `!==` instead of their regular counterparts `==` and `!=`.

## Occurrences
There are 54 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/JS-0050/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/JS-0050/occurrences/)

**Comment by joshijoe05** [comment]
Assign this issue to me, I would like to work

**Comment by priyanshu9899** [comment]
assign me this issue , i could fix this ..
