### ISSUE TITLE
(FLK-E231) Missing whitespace after `,`, `;`, or `:`

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#497]
## Description
There should be whitespace after the characters `,`, `;`, and `:`.

## Occurrences
There are 22 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/robotichead/NearBeach/issue/FLK-E231/occurrences/](https://app.deepsource.com/gh/robotichead/NearBeach/issue/FLK-E231/occurrences/)

**Comment by joshijoe05** [comment]
Hello, I would like to work on this issue. Please assign this to me

**Comment by joshijoe05** [comment]
I cannot find those occurences. Please unassign me

**Comment by joshith3501** [comment]
Hey, I would like to work on this issue. Can you assign this to me?
