### ISSUE TITLE
Update of UI

### ISSUE THREAD

**Issue by robotichead** [robotichead/NearBeach#9]
The UI is currently being worked on - however has not been mapped for this release as of yet. The following issues will need to be met:

- A style guide on how to call each HTML member i.e. <table class="table_content">
- The old Django Templates will need to be updated with the new UI. I am creating a kanboard to help track the progress of this
- All functionality will need to be tested after it has been applied

Regards
Luke

**Comment by robotichead** [comment]
https://github.com/robotichead/NearBeach/projects/3
The following project has been created to track the updating of the UI

**Comment by DatCodingGuy** [comment]
Style Guide:

- All page content has to be within a div with the id of "wrapper", this centers the content.
- Search bars within the content have to have the id of "input-field", it adds a margin below it
- Content headings should be within the "h2" tag
- Tables
  - It's recommended to change the cellspacing and cellpadding properties on the table to 0
  - Headers of the table have to have the id "table-header"
  - To get the alternating colour background in the table rows, add the "tr-background-changed" class

**Comment by robotichead** [comment]
@DatCodingGuy - can you please have a look at Organisations, customers, and Projects in development-0.5 branch. Could you look at improving how we can display the different sections in those models please.

**Comment by robotichead** [comment]
I am implementing the UI change in development-0.7 cycle. Everything will change.

**Comment by robotichead** [comment]
I have finished implementing the new UI across all templates. They now need testing and tweeking.
